### ISSUE TITLE
查询数据有问题？

### ISSUE THREAD

**Issue by xi-yue-233** [Azure99/GenshinPlayerQuery#30]
今天查询的时候突然发现会显示不全，只能显示一部分数据了
![image](https://user-images.githubusercontent.com/58218656/143556701-8bc5ad2a-4374-48f9-adf3-ddad8af7ef97.png)

**Comment by Lightczx** [comment]
米游社官方限制了查询他人数据的功能，现在查询他人数据只能获取8名角色，深渊无法获取队伍阵容

**Comment by Klamist** [comment]
> 米游社官方限制了查询他人数据的功能，现在查询他人数据只能获取8名角色，深渊无法获取队伍阵容

这8个就是玩家在游戏内搜UID时候资料展示的8个

**Comment by Azure99** [comment]
已修复
