### ISSUE TITLE
求大佬更新

### ISSUE THREAD

**Issue by dajuzju** [Azure99/GenshinPlayerQuery#31]
右边的角色截图显示不全，好像因为米游社更新了。现在只能显示部分角色

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Genshin/discussions/72

**Comment by Azure99** [comment]
米游社官方作出了限制，不能再查询其他玩家的全部角色和深渊信息了

**Comment by KimigaiiWuyi** [comment]
> 米游社官方作出了限制，不能再查询其他玩家的全部角色和深渊信息了

可以参考一下[我的](https://github.com/KimigaiiWuyi/GenshinUID/issues/34)
经过几周的测试应该没什么问题

**Comment by Azure99** [comment]
已修复，感谢@KimigaiiWuyi 提供的思路
