### ISSUE TITLE
Cannot pass captcha

### ISSUE THREAD

**Issue by Lakomka2204** [Azure99/GenshinPlayerQuery#35]
I don't know Chinese, can you please make English ver of site, i can't pass captcha, it says select all hieroglyphs in alphabetic order, but i don't know these so i can't use application
![image](https://user-images.githubusercontent.com/68611898/150639212-9f3e3029-95bf-4092-96fe-732f570dcce7.png)

**Comment by Lightczx** [comment]
Basically, if you are playing on global server, this app can't get the data you want.
This app can only get the data of CN server player.

**Comment by Lakomka2204** [comment]
Oh okay, because my login data was invalid after many attempts, so i
thought it's only for cn, but can i reprogram it for global?

**Comment by Lightczx** [comment]
You gonna need to capture the hoyolab package.
But I dont think hoyolob has same feature like display characters or spiralAbyss data.
Anyway if it exist some api like so,you can re-code this.

**Comment by Lightczx** [comment]
I remember someone had asked question about this, and he made this repo:
https://github.com/thesadru/genshinstats

Hope it helps you out

**Comment by Lakomka2204** [comment]
Thank you, is there any c# alternatives? Or only python?

**Comment by Lightczx** [comment]
I think only py for global
