### ISSUE TITLE
请问可以增加查看背包里面5星武器的功能吗

### ISSUE THREAD

**Issue by Donge-ying** [Azure99/GenshinPlayerQuery#4]
如题

**Comment by Azure99** [comment]
不可以, 但是可以汇总目前角色身上的所有装备(武器&圣遗物), 如有需要可以考虑开发

**Comment by Donge-ying** [comment]
还有一个问题，每次都要重新登录，有点繁琐

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Azure99<mailto:notifications@github.com>
发送时间: 2021年3月6日 16:50
收件人: Azure99/GenshinPlayerQuery<mailto:GenshinPlayerQuery@noreply.github.com>
抄送: sunfase<mailto:sunfase@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Azure99/GenshinPlayerQuery] 请问可以增加查看背包里面5星武器的功能吗 (#4)


不可以, 但是可以汇总目前角色身上的所有装备(武器&圣遗物), 如有需要可以考虑开发

―

**Comment by Azure99** [comment]
没太注意过, 抽时间看一下

**Comment by MakiseKurisu** [comment]
@Azure99 重新登陆我等会有个pr可以使操作更容易，但是如果不能解决cookie存活期最终还是要重新登陆

**Comment by Azure99** [comment]
@MakiseKurisu 前几天试了试, 发现从米哈游通行证页面登录后30分钟就会失效, 而从米游社登录则可以保活很久, 这两天比较忙 具体机制抽时间再看下
