### ISSUE TITLE
关于bbs-api

### ISSUE THREAD

**Issue by Yue-cn** [Azure99/GenshinPlayerQuery#42]
https://bbs-api.mihoyo.com/post/api/getForumPostList?forum_id=26&is_good=false&is_hot=true&page_size=20&sort_type=1

![E6668559DEBB1FAA3CB3469B22069602](https://user-images.githubusercontent.com/79188080/190843097-b73737be-c332-45b6-a880-9570889459c6.png)

似乎跟其他的API不一样,中间的random改成了string

主要是现在有什么办法可以成功GET

**Comment by BTMuli** [comment]
改referer

**Comment by jellyqwq** [comment]
iOS和安卓是两个DS验证模块
