### ISSUE TITLE
无法查询，提示米游社信息可能不完整

### ISSUE THREAD

**Issue by 201677I0318** [Azure99/GenshinPlayerQuery#47]
![image](https://github.com/Azure99/GenshinPlayerQuery/assets/32870663/b8c45fb0-5cf6-48d8-b64c-479a76fd8854)

5月26号上午一切正常，晚上查询报错如上图，查询他人的账号提示如上，但是查询自己的账号没有问题。

**Comment by liujunyi8652** [comment]
图灵测试，解决方案是在米游社app内任意进入他人的主页触发验证，手动通过之后再用查询器就行了

**Comment by yangyayu-last** [comment]
> 图灵测试，解决方案是在米游社app内任意进入他人的主页触发验证，手动通过之后再用查询器就行了

用米游社app进入他人的主页的时候，没有触发验证，重试二十次没有触发

**Comment by o0bladeAndsoul0o** [comment]
> 可以尝试启用米游社APP里的桌面小插件，来快速触发验证。

**Comment by Azure99** [comment]
已修复，在最近版本中添加了验证支持
