### ISSUE TITLE
闲聊，以及一些其他的

### ISSUE THREAD

**Issue by Dragon-Fish** [Azure99/GenshinPlayerQuery#7]
您好，感谢您的开源精神，针对原神玩家信息查询，我使用 Node.js 语言做了一个封装 https://github.com/Dragon-Fish/genshin-kit

但其实我最初也仅仅是从GitHub上搜集到了诸如您的项目，做了一些移植的工作，一旦米游社的协议发生变化，我还是得到您这里来《借鉴》😂

作为一个代码爱好者和原神玩家，我十分希望可以和您交流学习，但在这里说可能不太合适，如果您不介意可以通过 [这个 org](https://github.com/Wjghj-Project) 页面上的邮箱联系到我～

**Comment by Azure99** [comment]
已联系邮箱
